### ISSUE TITLE
Error while using with solace appliance

### ISSUE THREAD

**Issue by vishal6237** [solacecommunity/solace-prometheus-exporter#14]
Hi 
I am using this exporter with solace appliance and my broker SolOS version is 9.5.0.25.

I am able to see metrics related to VPN level, but when i try to access page for broker metrics.  Solace exporter started to throw below error

When solace exporter try to fetch data over http request using  “show system health” command, its throwing below error

msg=“unexpected result” command=“<rpc><show><system><health/><system/></show><rpc>”

**Comment by GreenRover** [comment]
Hi,

it seams that this line throws the error:
https://github.com/dabgmx/solace_exporter/blob/e9132f257c605fe79e2fd7436078ab0dc84829c4/solace_exporter.go
But in this case i would expect more fields in the error messages? Do you truncated the error message?

It seams that your broker does nit support data in expected format.
Can you please run:


```
curl -X POST -u user:password solacevmr:8080/SEMP \
  -H "content-type: application/xml" \
  -d "<rpc><show><system><health/></system></show ></rpc>"
```


and post the result?

**Comment by vishal6237** [comment]
Hi @GreenRover 

Thank you for quick response.

I ran the same curl command and got below error

<rpc-reply semp-version=“soltr/9_5”>
<parse-error>invalid message: schema validation error</parse-error>

**Comment by GreenRover** [comment]
@vishal6237 When you try to do the “show system health” on broker cli? May be your user dosent have the correct permission? 
@dabgmx Can it be that this command is a new one? But SolOs 9.5.0 is not that old.

**Comment by vishal6237** [comment]
Hi @GreenRover 

when i run command show system health on cli it give me below error
Invalid input command
                      Show system health
                                              ^
                       -> invalid parameter
Expected one of the following 
         detail   - show detailed information 
          post    - show power-on self testing(POST) status

**Comment by vishal6237** [comment]
When i run show system details
It give below output
System uptime :  49d 23h 10m 9s
Last Restart Reason : User request
Topic routing:
      Subscription Exceptions: Enabled
      Subscription Exceptions Defer: Enabled

**Comment by GreenRover** [comment]
i will check this in the frist januar days

**Comment by dabgmx** [comment]
Hi @vishal6237, as stated in the disclaimer, the exporter has not yet been tested against Solace hardware appliances, only software and SaaS brokers. There might be differences in the CLI/SEMPV1 command set. I will try to grab access to an appliance and do some tests myself. Meanwhile your findings are most valuable inputs.

**Comment by GreenRover** [comment]
@vishal6237 Is it an appliance? Or a software broker? Can you please specify exactly what you use.
The exporter is only tested for software broker.

**Comment by vishal6237** [comment]
Hi @GreenRover 

yes, I am using appliance. Also i have read about the disclaimer that this was not tested on appliance. But i wanted to give it a try as need to use it on appliance to produce some metrics

thank you for your help on this. Please let me know if i can do some changes in go file to make it work.

**Comment by GreenRover** [comment]
Fix it and provide a pull request or please @dabgmx to ship me one :-)

**Comment by GreenRover** [comment]
I checked no on my oldest broker "9.3.0.22":
```
ubuntu-s-4vcpu-8gb-fra1-01> show system
 Expected one of the following:
      health  - Show health information.
      detail  - Show detailed information.
      post    - Show Power-On Self Test (POST) status
```

```
ubuntu-s-4vcpu-8gb-fra1-01> show system detail

System Uptime: 43d 21h 10m 56s
Last Restart Reason: None

Scaling:
   Max Connections: 1000
   Max Queue Messages: 100M

Topic Routing:
   Subscription Exceptions: Enabled
   Subscription Exceptions Defer: Enabled

System Resources for Container

System Resource              Available    Required     Units
---------------------------- ------------ ------------ ----------
CPU
  Cores                      4            2
Memory
  Host Virtual Memory        7.8          5.8          GiB
  Memory Cgroup Limit        7.8          4.9          GiB
  Shared Memory              2.0          1.0          GiB
Storage Devices
  /dev/vda1                  154.9 Mi     5.9 Mi       1K-Blocks
    contains: adb
    contains: adb-backup
    contains: diagnostics
    contains: jail
    contains: spool
    contains: var
  overlay                    154.9 Mi     1.4 Mi       1K-Blocks
    contains: root
    contains: config
```

```
ubuntu-s-4vcpu-8gb-fra1-01> show system health

Statistics since:  Nov 09 2020 22:56:19 UTC

                   Units   Min      Max      Avg      Curr     Thresh    Events
                   ------  -------  -------  -------  -------  --------  -------
Disk Latency       us      336      6244654  6059     1235     10000000  0
Compute Latency    us      900      101891   1122     1112     500000    0
Network Latency    us      0        0        0        0        2000000   0
Mate-Link Latency  us      0        0        0        0        2000000   0
```

**Comment by GreenRover** [comment]
@dabgmx Any updates?

**Comment by vishal6237** [comment]
Hi Heiko,

sorry for late reply. 
Actually i am a beginner with golang.
I am using 9.5.0.25 version on appliance
 About compliance command

“show system health” command is not available in appliance on version 9.5.0.25
Only “show system detail” and “ show system post” is available.

**Comment by vishal6237** [comment]
https://docs.solace.com/Solace-CLI/CLI-Reference/APPL_CLI_Commands.html

Commands on above URL are only available on appliance.
I have tried using docker container of solace on same version 9.5.0.25. "show system health" is available on docker but not on appliance.

**Comment by GreenRover** [comment]
@dabgmx @TamimiGitHub I think here i need access to an appliance to really test it. Or @dabgmx you will implement it (may be in pair), i guess you have a testing appliance in office? Or may be some one of you folks can create curl samples to let me try it blind.

**Comment by uherbstsolace** [comment]
I can test this on our lab appliance.

**Comment by GreenRover** [comment]
@uherbstsolace any updates?

**Comment by GreenRover** [comment]
@dabgmx Do solace still wants to help here? Otherwise i have to close this issues.

@vishal6237 Please gibe the newest version of exporter a try, now it is very more modular and let you choose only appliance compatible modules

**Comment by dabgmx** [comment]
Please leave it open, I will test with @uherbstsolace when I have a timeslot

**Comment by uherbstsolace** [comment]
1. I tested the current version with an appliance, no issues found
2. "show system health" is not available in any appliance SolOS version (tested with 9.4 and 9.8) - so we need a flag for the exporter to say "this is an appliance" or (maybe better) we need code to handle that exception, because that exception is not just a bug.

**Comment by GreenRover** [comment]
@uherbstsolace You cam confirm that non of those metrics is available for appliance: 
https://github.com/solacecommunity/solace-prometheus-exporter/blob/master/solace_prometheus_exporter.go

may be on different position?

If those are not available i will improve the error message and advice that the Health scrape target:
https://github.com/solacecommunity/solace-prometheus-exporter

is not available for applicances

**Comment by GreenRover** [comment]
Still no feedback from solace. Clothing the issue
