### ISSUE TITLE
Update link on prometheus exporters page

### ISSUE THREAD

**Issue by dabgmx** [solacecommunity/solace-prometheus-exporter#16]
Update here
https://github.com/prometheus/docs/blob/77eb61193ead3c45a4d51260f15baf2651f30e11/content/docs/instrumenting/exporters.md

**Comment by GreenRover** [comment]
@dabgmx Any updates?

**Comment by GreenRover** [comment]
PR created: https://github.com/prometheus/docs/pull/1850

**Comment by GreenRover** [comment]
PR was merged
