### ISSUE TITLE
Add License + Review Missing Items from SC Template

### ISSUE THREAD

**Issue by Mrc0113** [solacecommunity/solace-prometheus-exporter#17]
Add License + Review Missing Items from Solace Community Repo Template

**Comment by GreenRover** [comment]
I replaced "TODO: Fill in with quick explanation and maybe an arch diagram from the video. " in doku.
Do you think its ok now? I not really know what to write there any more.

**Comment by Mrc0113** [comment]
Looks good to me. Thanks @GreenRover. Closing this issue.
