### ISSUE TITLE
Update Docker build rules with new dockerhub org scope

### ISSUE THREAD

**Issue by TamimiGitHub** [solacecommunity/solace-prometheus-exporter#18]
after #15 update docker build rules to include publishing to new dockerhub org

**Comment by TamimiGitHub** [comment]
Hey @dabgmx, I have created a dockerhub solace community org https://hub.docker.com/orgs/solacecommunity we can push the image on

**Comment by TamimiGitHub** [comment]
Build rules updated https://hub.docker.com/repository/docker/solacecommunity/solace-prometheus-exporter

If you think this is good, you can go ahead and close this issue

**Comment by GreenRover** [comment]
The build jop only create the latest.
The old one also was Building all tags starting with "v"
https://github.com/solacecommunity/solace-prometheus-exporter/tags

**Comment by TamimiGitHub** [comment]
@GreenRover I can invite you the solacecommunity dockerhub org so you can check out the build rules there, what is your docker handle?

**Comment by GreenRover** [comment]
https://hub.docker.com/u/greenrover

**Comment by TamimiGitHub** [comment]
Added

**Comment by GreenRover** [comment]
It only builds new release. 
Now, after create a new minor release, we have a stable release on dockerhub
