### ISSUE TITLE
Can't see metrics

### ISSUE THREAD

**Issue by shivalikac** [solacecommunity/solace-prometheus-exporter#25]
Hi
I want to use solace Prometheus exporter to monitor the performance of my solace software running as a docker container.
I installed the git hub package, started the solace-exporter container. When I go to the localhost:9628, and any sub page, I do not have the metrics. All I get is:

HELP broker_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which broker was built.
TYPE broker_build_info gauge
broker_build_info{branch="",goversion="go1.13.15",revision="",version=""} 1
HELP solace_up Was the last scrape of Solace broker successful.
TYPE solace_up gauge
solace_up 0

This is on http://localhost:9628/solace-std

As per the video tutorial I should be able to see the metrics. Can you please help with what is going wrong?

**Comment by GreenRover** [comment]
Please provide the output of
docker logs solace-exporter

**Comment by shivalikac** [comment]
**docker logs solace-exporter:**

level=info ts=2021-03-22T11:15:02.352Z caller=solace_exporter.go:1557 msg="Starting solace_exporter" version=1.003004e+06
level=info ts=2021-03-22T11:15:02.352Z caller=solace_exporter.go:1558 msg="Build context" context="(go=go1.13.15, user=, date=)"
level=info ts=2021-03-22T11:15:02.352Z caller=solace_exporter.go:1560 msg=Scraping listenAddr=0.0.0.0:9628 scrapeURI="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile" username=admin sslVerify=false timeout=5s redundancy=false
level=info ts=2021-03-22T11:15:12.168Z caller=solace_exporter.go:1650 handlehttprequest=scope vpn=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:12.168Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:15:12.254Z caller=solace_exporter.go:510 msg="Can't scrape VpnSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:15:14.428Z caller=solace_exporter.go:1650 handlehttprequest=scope broker=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:14.429Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:15:14.452Z caller=solace_exporter.go:154 msg="Can't scrape getVersionSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:15:23.045Z caller=solace_exporter.go:1650 handlehttprequest=scope broker=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:23.049Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:15:23.083Z caller=solace_exporter.go:154 msg="Can't scrape getVersionSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:15:23.084Z caller=solace_exporter.go:1650 handlehttprequest=scope brokerStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:23.086Z caller=solace_exporter.go:1470
level=info ts=2021-03-22T11:15:23.086Z caller=solace_exporter.go:1650 handlehttprequest=scope vpn=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:23.090Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:15:23.187Z caller=solace_exporter.go:510 msg="Can't scrape VpnSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:15:23.187Z caller=solace_exporter.go:1650 handlehttprequest=scope vpnStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:23.187Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:15:23.212Z caller=solace_exporter.go:849 msg="Can't scrape ClientSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:15:26.473Z caller=solace_exporter.go:1650 handlehttprequest=scope brokerDetails=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:26.474Z caller=solace_exporter.go:1470
level=info ts=2021-03-22T11:15:26.474Z caller=solace_exporter.go:1650 handlehttprequest=scope vpnDetails=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:15:26.477Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:15:26.499Z caller=solace_exporter.go:1226 msg="Can't scrape QueueDetailSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:18:43.519Z caller=solace_exporter.go:1650 handlehttprequest=scope broker=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:18:43.519Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:18:43.538Z caller=solace_exporter.go:154 msg="Can't scrape getVersionSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:18:43.543Z caller=solace_exporter.go:1650 handlehttprequest=scope brokerStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:18:43.543Z caller=solace_exporter.go:1470
level=info ts=2021-03-22T11:18:43.543Z caller=solace_exporter.go:1650 handlehttprequest=scope vpn=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:18:43.544Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:18:43.564Z caller=solace_exporter.go:510 msg="Can't scrape VpnSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-22T11:18:43.565Z caller=solace_exporter.go:1650 handlehttprequest=scope vpnStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-22T11:18:43.565Z caller=solace_exporter.go:1470
level=error ts=2021-03-22T11:18:43.582Z caller=solace_exporter.go:849 msg="Can't scrape ClientSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-24T04:14:23.764Z caller=solace_exporter.go:1557 msg="Starting solace_exporter" version=1.003004e+06
level=info ts=2021-03-24T04:14:23.764Z caller=solace_exporter.go:1558 msg="Build context" context="(go=go1.13.15, user=, date=)"
level=info ts=2021-03-24T04:14:23.764Z caller=solace_exporter.go:1560 msg=Scraping listenAddr=0.0.0.0:9628 scrapeURI="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile" username=admin sslVerify=false timeout=5s redundancy=false
level=info ts=2021-03-24T04:14:35.963Z caller=solace_exporter.go:1650 handlehttprequest=scope broker=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:14:35.971Z caller=solace_exporter.go:1470
level=error ts=2021-03-24T04:14:37.975Z caller=solace_exporter.go:154 msg="Can't scrape getVersionSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-24T04:14:38.006Z caller=solace_exporter.go:1650 handlehttprequest=scope brokerStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:14:38.007Z caller=solace_exporter.go:1470
level=info ts=2021-03-24T04:14:38.008Z caller=solace_exporter.go:1650 handlehttprequest=scope vpn=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:14:38.008Z caller=solace_exporter.go:1470
level=error ts=2021-03-24T04:14:40.019Z caller=solace_exporter.go:510 msg="Can't scrape VpnSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-24T04:14:40.021Z caller=solace_exporter.go:1650 handlehttprequest=scope vpnStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:14:40.021Z caller=solace_exporter.go:1470
level=error ts=2021-03-24T04:14:42.023Z caller=solace_exporter.go:849 msg="Can't scrape ClientSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-24T04:15:48.856Z caller=solace_exporter.go:1650 handlehttprequest=scope broker=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:15:48.857Z caller=solace_exporter.go:1470
level=error ts=2021-03-24T04:15:50.859Z caller=solace_exporter.go:154 msg="Can't scrape getVersionSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-24T04:15:50.862Z caller=solace_exporter.go:1650 handlehttprequest=scope brokerStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:15:50.862Z caller=solace_exporter.go:1470
level=info ts=2021-03-24T04:15:50.862Z caller=solace_exporter.go:1650 handlehttprequest=scope vpn=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:15:50.866Z caller=solace_exporter.go:1470
level=error ts=2021-03-24T04:15:52.868Z caller=solace_exporter.go:510 msg="Can't scrape VpnSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"
level=info ts=2021-03-24T04:15:52.871Z caller=solace_exporter.go:1650 handlehttprequest=scope vpnStats=scrapeURI http://localhost:8080/#/msg-vpns/ZGVmYXVsdA/properties/stats?count20&cursor&displayFormattile=(MISSING)
level=info ts=2021-03-24T04:15:52.872Z caller=solace_exporter.go:1470
level=error ts=2021-03-24T04:15:54.877Z caller=solace_exporter.go:849 msg="Can't scrape ClientSemp1" err="Get http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile/SEMP: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" broker="http://localhost:8080/#/msg-vpns/ZGVmYXVsdA==/properties/stats?count=20&cursor=&displayFormat=tile"

**Comment by shivalikac** [comment]
**For your reference:
The solace_prometheus_exporter.ini file:**

[solace]
# Address to listen on for web interface and telemetry.
listenAddr=0.0.0.0:9628
# Base URI on which to scrape Solace broker.
scrapeUri=http://localhost:8080
# Basic Auth username for http scrape requests to Solace broker.
username=admin
# Basic Auth password for http scrape requests to Solace broker.
password=admin
# Timeout for http scrape requests to Solace broker.
timeout=5s
# Flag that enables SSL certificate verification for the scrape URI.
sslVerify=false
# Flag that enables scrape of redundancy metrics. Should be used for broker HA groups.
redundancy=false


**My prometheus.yml file:**
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:15692']

  - job_name: 'solace-std'
    scrape_interval: 15s
    metrics_path: /solace-std
    static_configs:
      - targets:
              - https://admin:admin@localhost:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: solace-exporter:9628
~

**Comment by GreenRover** [comment]
Docker is isulating the pods from each other. Having internally different ips. With the fact that localhost of the exporter is not the same as of the broker. Please try to use the main ip of the host insted of localhost at this point

**Comment by shivalikac** [comment]
I made the ScrapeURI, http://127.0.0.1:8080 
Still the same issue in the logs:
level=info ts=2021-03-25T05:12:27.501Z caller=solace_exporter.go:1650 handlehttprequest=scope vpnStats=scrapeURI http://127.0.0.1:8080=(MISSING)
level=error ts=2021-03-25T05:12:27.501Z caller=solace_exporter.go:849 msg="Can't scrape ClientSemp1" err="Get http://127.0.0.1:8080/SEMP: dial tcp 127.0.0.1:8080: connect: connection refused" broker=http://127.0.0.1:8080

**Comment by GreenRover** [comment]
Dont use 127.0.0.1 , not use the loopback interface. Those are. Fot the same for exporter pod and broker pod.

What will work:
- Use real ip of host
- If you use docker compose, the pod name of the broker (docker compose also creats a virtual network of pods of the same yaml file)

**Comment by shivalikac** [comment]
Hi, Thanks for your help! It is working with the real ip
