### ISSUE TITLE
How to get the "Incoming Message Rate" and "Outgoing Message Rate" of a VPN?

### ISSUE THREAD

**Issue by flyisland** [solacecommunity/solace-prometheus-exporter#38]
I've tried the `/solace?m.VpnStats=*|*&m.Vpn=*|*` query, but found nothing about message rate inside the result.

**Comment by GreenRover** [comment]
This wont help here. Rates should in prometheus to be calculated always.
VpnStats will provide your:
```
solace_vpn_rx_msgs_total
solace_vpn_tx_msgs_total
```

```
rate(solace_vpn_rx_msgs_total{vpn_name="yourVpn"}[5m])
rate(solace_vpn_tx_msgs_total{vpn_name="yourVpn"}[5m])
```

Enabling you to calculate rates:
![image](https://user-images.githubusercontent.com/512850/158196881-88516bb9-4f3a-484b-a09f-23908c01888d.png)

**Comment by flyisland** [comment]
@GreenRover thanks for the explanation.

Since the Solace broker has already had rate information like "rate per second" and "rate per min", my first thought is to simply show directly in Grafana.
