### ISSUE TITLE
Environment variables for proxy not respected

### ISSUE THREAD

**Issue by cb149** [solacecommunity/solace-prometheus-exporter#39]
I tried using the Docker image of v1.4.3 to get metrics from my Solace cloud broker. The image is deployed to OpenShift and has to use a proxy.
I set the environment variables http_proxy, https_proxy, HTTP_PROXY and HTTPS_PROXY but I always got the error:
```
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
I cloned the project and changed
https://github.com/solacecommunity/solace-prometheus-exporter/blob/master/solace_prometheus_exporter.go#L77
from
```go
tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: !e.config.sslVerify}}
```
to 
```go
tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: !e.config.sslVerify}, Proxy: http.ProxyFromEnvironment}
```
and now it works.

I don't have any experience with go, so I am wondering if this change is necessary or how else you would run this behind a proxy.

**Comment by GreenRover** [comment]
Fix was released
