### ISSUE TITLE
Is there any metrics talking about the solace queue and client mapping ?

### ISSUE THREAD

**Issue by lion200816** [solacecommunity/solace-prometheus-exporter#44]
I want to know how many clients and their names connecting one queue ? But seems I can't find one metrics showing this.

**Comment by dabgmx** [comment]
The Bind Count metric is already available in target QueueDetails. I don't think it makes sense to send the whole list of client names to Prometheus.

**Comment by lion200816** [comment]
@dabgmx  Yes, thanks. The solace_queue_binds shows the number of consumers. And why I need the queue and consumer name mapping is that I want to get the queue-application relationship as historical information more easier from Prometheus. When doing trouble shooting like one queue has no consumer suddenly, it can be easier to know which application has problem. Thank you all the same.

**Comment by GreenRover** [comment]
@lion200816 You speaking here about a very Serios amount of data. This would harm the broker as well as Prometheus.
For example: 4000 Clients are connected to your broker each client is consuming ~2 queues. Than you would end up with 8000 metrics for Prometheus. This would be in this case ~100MB memory for Prometheus if you scrape those metrics all 5 minutes.
This would also increase the scaping page size and scraping time. In short those big Prometheus endpoints would be against all Prometheus best practices.
If you want to implement it by your own. Please to it as an separate scrape target with an big warning that this is very dangerous when having more than 100 clients.

**Comment by lion200816** [comment]
@GreenRover Well understood on the risk.  We are considering to implement our requirement via other way. Thanks.
