### ISSUE TITLE
Client.Timeout error

### ISSUE THREAD

**Issue by andyzuchettosonos** [solacecommunity/solace-prometheus-exporter#58]
I have been successfully using the exporter for several months via the latest docker hub image. We can see our Solace metrics in prometheus and grafana. However, I recently noticed gaps every once and a while in the metrics and looking at the logs on the solace-prometheus-exporter container I can see the following two errors a handful over times every day (I've removed our Solace URL). 

`ts=2023-11-06T21:09:17.521Z caller=log.go:124 level=error msg="Can't scrape ClientStatSemp1" err="Post \"https://xxxxxx/SEMP\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" broker=https://xxxxxx`

`ts=2023-11-06T19:14:47.545Z caller=log.go:124 level=error msg="Can't decode ClientStatSemp1" err="context deadline exceeded (Client.Timeout or context cancellation while reading body)" broker=https://xxxxxx`

I updated the timeout env var as follows to see if that would eliminate the error, but it did not. 
`SOLACE_TIMEOUT=300s`

Also, at the start of the container log I can see what appears to be the timeout getting set (I've removed our Solace URL and username).

`ts=2023-11-06T16:33:44.491Z caller=log.go:124 level=info msg=Scraping listenAddr=http://0.0.0.0:8080 scrapeURI=https://xxxxxx username=xxxxxx sslVerify=false timeout=5m0s`

**Comment by aaron-613** [comment]
Out of curiosity: how many clients do you have connected to your broker?

**Comment by GreenRover** [comment]
Sorry but this is a broker problem. I expect you have very much clients and the broker reached it cpu linit. Please contact solace for assist

**Comment by aaron-613** [comment]
Are the SEMP requests being paged out in reasonably sized batches, and using the `<more-cookie>` to fetch the next batch..?

**Comment by GreenRover** [comment]
@aaron-613  The exporter uses the default batch size and more-cookie to fetch next batch:
https://github.com/solacecommunity/solace-prometheus-exporter/blob/master/semp/getClientStatsSemp1.go#L57

@andyzuchettosonos The exporter documentation is saying:

scrape target | vpn filter supports | item filter supported | performance impact | corresponding cli cmd | supported by
-- | -- | -- | -- | -- | --
ClientStats | yes | no | may harm broker if many clients | show client itemFilter stats (paged) | software, appliance

**Comment by andyzuchettosonos** [comment]
@aaron-613 We only have a single client for the solace-prometheus-exporter, but we do have hundreds of clients connected to the Solace message broker at any given time publishing and receiving messages. We are not close to our max client connections though, which is 1000. 

I'm not seeing any broker errors on other clients, just on these SEMP monitoring calls.

**Comment by GreenRover** [comment]
Ok this is to much. Eighter dont use ClientStats metrics or add more cpu power to the broker

**Comment by GreenRover** [comment]
Issue closed caused by inactivity
