### ISSUE TITLE
[Feature]: new/missing metrics

### ISSUE THREAD

**Issue by osd42** [solacecommunity/solace-prometheus-exporter#66]
### Feature Description

Hello,
Here is a list of metrics I am not able to find with the Solace Prometheus Exporter. There are sometimes equivalent metrics coming from a different SEMPv1 query.

| Ref / Group | SEMP v1 Request Body | SEMP v1 Response path | name |
| --- | --- | --- | --- |
| Subscription Management | rpc/show/smrp/subscriptions/summary | rpc/show/smrp/subscriptions/total-subscriptions | total-subscriptions |
| Subscription Management | rpc/show/smrp/subscriptions/summary | rpc/show/smrp/subscriptions/total-unique-subscriptions | total-unique-subscriptions |
| Subscription Management | rpc/show/smrp/subscriptions/summary | rpc/show/smrp/subscriptions/total-client-subscriptions | total-client-subscriptions |
| Ingress Flows | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/ingress-flows-allowed | ingress-flows-allowed |
| Ingress Flows | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/ingress-flow-count | ingress-flow-count |
| Egress Flows | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/active-flow-count | active-flow-count |
| Egress Flows | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/inactive-flow-count | inactive-flow-count |
| Egress Flows | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/browser-flow-count | browser-flow-count |
| Endpoints utilization | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/message-spool-entities-allowed-by-qendpt | message-spool-entities-allowed-by-qendpt |
| Endpoints utilization | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/message-spool-entities-used-by-queue | message-spool-entities-used-by-queue |
| Endpoints utilization | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/current-messages-spooled | current-messages-spooled |
| Endpoints utilization | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/message-spool-entities-used-by-dte | message-spool-entities-used-by-dte |
| Transacted sessions | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/max-transacted-sessions | max-transacted-sessions |
| Transacted sessions | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/transacted-sessions-used | transacted-sessions-used |
| Transacted sessions | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/max-transactions | max-transactions |
| Transacted sessions | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/transactions-used | transactions-used |
| Disk usage | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/current-persist-usage | current-persist-usage (MB) |
| Disk usage | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/current-rfad-usage | current-rfad-usage (ADB) (MB) |
| Messages currently spooled | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/rfad-messages-currently-spooled | rfad-messages-currently-spooled (ADB) |
| Messages currently spooled | rpc/show/message-spool/detail | rpc/show/message-spool/message-spool-info/disk-messages-currently-spooled | disk-messages-currently-spooled |
| Configuration Synchronization | rpc/show/config-sync | rpc/show/config-sync/status/admin-status | config-sync-enabled |
| Configuration Synchronization | rpc/show/config-sync | rpc/show/config-sync/status/oper-status | config-sync-up |
| Redundancy | rpc/show/redundancy/detail | rpc/show/redundancy/redundancy-mode | redundancy-mode |
| Redundancy | rpc/show/redundancy/detail | rpc/show/redundancy/oper-status/adb-link-up | adb-link-up |
| Redundancy | rpc/show/redundancy/detail | rpc/show/redundancy/oper-status/adb-hello-up | adb-hello-up |
| Queues detail | rpc/show/queue/name/*/name/detail | rpc/show/queue/queues/queue/info/total-delivered-unacked-msgs | total-delivered-unacked-msgs |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/current-ingress-rate-per-second | current-ingress-rate-per-second |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/current-ingress-byte-rate-per-second | current-ingress-byte-rate-per-second |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/current-egress-rate-per-second | current-egress-rate-per-second |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/current-egress-byte-rate-per-second | current-egress-byte-rate-per-second |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/average-ingress-rate-per-minute | average-ingress-rate-per-minute |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/average-ingress-byte-rate-per-minute | average-ingress-byte-rate-per-minute |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/average-egress-rate-per-minute | average-egress-rate-per-minute |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/average-egress-byte-rate-per-minute | average-egress-byte-rate-per-minute |
| Client stats | rpc/show/client/name/*/name/stats | rpc/show/client/primary-virtual-router/client/stats/egress-discards/message-spool-congestion | message-spool-congestion |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/average-ingress-rate-per-minute | cluster-average-ingress-rate-per-minute |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/average-egress-rate-per-minute | cluster-average-egress-rate-per-minute |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/average-ingress-byte-rate-per-minute | cluster-average-ingress-byte-rate-per-minute |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/average-egress-byte-rate-per-minute | cluster-average-egress-byte-rate-per-minute |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/current-ingress-rate-per-second | cluster-current-ingress-rate-per-second |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/current-egress-rate-per-second | cluster-current-egress-rate-per-second |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/current-ingress-byte-rate-per-second | cluster-current-ingress-byte-rate-per-second |
| Client global stats | rpc/show/stats/client | rpc/show/stats/client/global/stats/current-egress-byte-rate-per-second | cluster-current-egress-byte-rate-per-second |
| Bridge detail | rpc/show/bridge/bridge-name-pattern/*/bridge-name-pattern/detail | rpc/show/bridge/bridges/bridge/remote-message-vpn-list/remote-message-vpn/connection-state | connection-state |

_Notes:_
- I converted the XML payloads because it is not easy to write \<anchors/\> but I can share privately the internal document which compares 300 metrics over 3 different Solace monitoring tools.
- We never get answer from the scope "Disk" (solace cloud, gcp, on prem) so the Disk metrics could be missing from my comparison work.

Do you find these metrics relevant ? Is it be possible to add some of these missing metrics ?

Best regards !

### Use Case

Our goal (monitoring & observability team) is to ensure our Solace team will be able to keep their key metrics while migrating the old monitoring tool to a new monitoring tool based on the Solace Prometheus Exporter.
Some more metrics will cover the needs of all our teams with a unique tool.

### Proposed Solution

- check if metrics are already available from another SEMP query
- add relevant new metrics to an existing or a new Solace Prometheus Exporter scopes

**Comment by GreenRover** [comment]
Hello @osd42 i reviewed your list:
- "rpc/show/smrp/subscriptions/summary" returns a very huge amount of Information. I guess this is a very expensive operation for the broker to collect those information's. For a medium loaded test broker it took 333ms to query this Information what is a very long time. Why you want to query this Information. Please explain your use case.
- "Ingress Flows", "Egress Flows", "Endpoints utilization", "Transacted sessions" , "Disk usage", "Messages currently spooled", "Queues detail", "Client global stats" looks like very useful enhancements. But i have for most of the values no clue what they are used for.  Please ask solace to provide a for each of your proposed values:
  - A brief description like in this example: https://github.com/solacecommunity/solace-prometheus-exporter/blob/master/semp/metricDesc.go#L110
  - A short text explaining how those values correlate together. How those could be used in alert rules and visualisations.
  - "Configuration Synchronization" are provided via `ConfigSync`
- "Redundancy" Here is my used case just to monitor the metric `solace_system_redundancy_up`. Because in monitoring i only need to know if this it works or not. Imho debug the details can be done via cli. Please examplain where you see the benefit from your requested metrics?
- "Client stats" Here you attrackt a very huge ammount of data. Scraping this information will defently harm a huge broker. I would strongly advise against collecting this information.
- "Bridge detail" Please explain the difference to the metrics: `solace_bridge_inbound_operational_state` && `solace_bridge_outbound_operational_state` aka Request "rpc/show/bridge/bridge-name-pattern/*/bridge-name-pattern" Why you need to monitor the remote message von that is connected? The connection state of the bridge should be enough?

**Comment by osd42** [comment]
Hello @GreenRover 
I am still without answers from my colleagues. Sorry !

I think we just want the metrics we had on others monitoring systems without any consideration of the overhead cost on the Solace nodes. So your answer is a new approach and requires a lot of analysis.

I close the request. But I'll ask again my Solace team colleagues to react to your answer.

Thank you for your answers !
