### ISSUE TITLE
[Feature]: Support for OAuth authentication

### ISSUE THREAD

**Issue by pascalre** [solacecommunity/solace-prometheus-exporter#70]
### Feature Description

Currently the solace-prometheus-exporter does only support basic auth. OAuth could be used as a more secure way of authentication.

### Use Case

Basic Authentication sends the username and password with each request in plain text, which can be intercepted and compromised. OAuth, on the other hand, uses tokens and cryptographic signatures, reducing the risk of exposing credentials.

**Comment by pascalre** [comment]
Exactly, authentification against the PubSub+ Event Broker. I am not experienced in Go, but I may give it a try at some point.

**Comment by Mrc0113** [comment]
Awesome @pascalre, if you get stuck feel free to start a discussion over at [Solace Community](https://solace.community). 

Unfortunately our SEMP docs don't yet do this, but our Solace Cloud API docs let you copy code in different languages and uses oauth tokens so maybe you can look at the Golang example (choose language at the top right) over here as a starting point: https://api.solace.dev/cloud/reference/getapplicationdomains

**Comment by GreenRover** [comment]
Issue closed caused by inactivity

**Comment by GreenRover** [comment]
@pascalre Please have a look at: #132
