### ISSUE TITLE
[Bug]: Bad list of scopes in the log filter (Global, ReplicationStats)

### ISSUE THREAD

**Issue by osd42** [solacecommunity/solace-prometheus-exporter#73]
### Bug Description

Hello, 
We are using exporter 1.7.2. There is a missing log filter for the scope GlobalSystemInfo and we noticed that some filter scope do not even exist.

`ts=2024-07-25T06:51:51.156Z caller=exporter.describe.go:24 level=error msg="Unexpected data source name: GlobalSystemInfo" permitted=Redundancy,VpnStats,TopicEndpointDetails,ClientConnections,VpnSpool,Memory,Spool,ReplicationStats,Vpn,Disk,ClientSlowSubscriber,ClusterLinks,TopicEndpointRates,Global,VpnReplication,ConfigSyncVpn,QueueDetails,Health,Interface,Bridge,QueueRates,TopicEndpointStats,ConfigSync,ConfigSyncRouter,Client,ClientMessageSpoolStats,BridgeStats,QueueStats,QueueStatsV2,Version,StorageElement,GlobalStats,ClientStats`

This error seems to be a false-positive.

Regards
Charles

### Expected Behavior

From a quick sight, it seems that the "Global" scope filter should be replaced by "GlobalSystemInfo"
It seems that the list of filtered scopes is incorrect: ReplicationStats does not exist
(I did not check the whole list)

### Steps to Reproduce

- send a query to any broker with URI `/solace?m.GlobalSystemInfo=*|*`
- check the logs of the exporter

**Comment by GreenRover** [comment]
Was fixed
