### ISSUE TITLE
[Feature]: Adding SolOS version as a label for "Version" metric

### ISSUE THREAD

**Issue by lwyic** [solacecommunity/solace-prometheus-exporter#78]
### Feature Description

Currently, "Version" returns a long number which is not very human readable. I don't know of a way to change it back to the "A.B.C.D" format in grafana. I suggest that we could add a label to the metric to encode the version number in the human readable format.

### Use Case

It makes it easier to display a human readable SolOS version on Grafana or other dashboard tools.

**Comment by GreenRover** [comment]
A new label creates in prometheus a new metric what make its hard to visualize the version history.

To decode the version history see this example dashboard:

grafana/solace-broker-dashboard.pdf

**Comment by lwyic** [comment]
That works. Thanks.
