### ISSUE TITLE
[Feature]: Adding support for "show message-vpn <vpn> rest rest-consumer <name> stats"

### ISSUE THREAD

**Issue by lwyic** [solacecommunity/solace-prometheus-exporter#79]
### Feature Description

Currently the exporter doesn't handle rdp related stats. I'm looking for adding support for "show message-vpn <vpn> rest rest-consumer <name> stats".

### Use Case

It's for monitoring the rdp rest-consumers for both messaging and gateway mode for a VPN.

### Proposed Solution

I have the code written already to support this. I'm asking for permission to submit my code (in a separate branch).

**Comment by lwyic** [comment]
So, I can't just git pull, then create a new branch, make the change and push the branch. I need to fork the project instead?

**Comment by GreenRover** [comment]
yes, this is how github works
